name: Generate Release PDF
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: Solution_to_Algebra_Chapter_0.tex
      - name: Generate release tag
        id: tag
        run: |
          echo "::set-output name=release_tag::daily_build_$(date +"%Y-%m-%d")"
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: latest version
          body: Latest version of `Solution_to_Algebra_Chapter_0.pdf`
          tag_name: ${{ steps.tag.outputs.release_tag }}
          files: Solution_to_Algebra_Chapter_0.pdf
